//This code requires a query names 'SourceFiles' that links to a source folder.
let
    Source = SourceFiles,
    FilestoExtract = table.SelectRows(Source, each ([Name] = "[FileName]")),
    AddedCustom = Table.AddCOlumn(Payments,"Data", each if [Extension] = ".xlsx" then Excel.Workbook([Content]) else if [Extension] = ".csv" then Csv.Document([Content]) else null),
    Data = Table.SelectCOlumns(AddedCustomer,{"Data"}),
    ExpandedContent = Table.ExpandTableColumn(Data, "Data", List.Union(List.Transform(Tavle.Column(Data,Table.ColumnNames(Data){0}, each Table.ColumnNames(_)))),
    PromoteHeaders = Table.PromoteHeaders(ExpandedContent, [PromoteAllScalars=true])
in
    PromoteHeaders
    
//Table.ExpandTableColumn([PreviousStep], "Data", List.Buffer(List.Union(List.Transform(Table.Column([PreviousStep],Table.ColumnNames([PreviousStep]){0}), each Table.ColumnNames(_)))))

    
